# Generated by Django 4.1.1 on 2022-12-04 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='layanan',
            fields=[
                ('idlayanan', models.AutoField(primary_key=True, serialize=False)),
                ('jenislayanan', models.CharField(max_length=30)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pemesanan',
            fields=[
                ('idpemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('metodeambil', models.CharField(max_length=35)),
                ('namadelivery', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pelanggan',
            fields=[
                ('idpelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('statuscuci', models.CharField(max_length=50)),
                ('statushelm', models.CharField(max_length=50)),
                ('namapelanggan', models.CharField(max_length=50)),
                ('nohp', models.IntegerField()),
                ('alamat', models.CharField(max_length=50)),
                ('tanggalpesan', models.DateField()),
                ('idlayanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.layanan')),
            ],
        ),
        migrations.CreateModel(
            name='detaillayanan',
            fields=[
                ('iddetaillayanan', models.AutoField(primary_key=True, serialize=False)),
                ('idpelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pelanggan')),
                ('idpemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pemesanan')),
            ],
        ),
    ]
